site_name: APIFlask
site_description: Web APIs for Flask.
site_url: https://apiflask.com
docs_dir: docs
theme:
  name: material
  custom_dir: docs/_templates
  logo: _assets/white-logo.png
  favicon: _assets/favicon.png
  palette:
    primary: deep orange
  icon:
    repo: fontawesome/brands/github
  language: en
repo_url: https://github.com/greyli/apiflask
repo_name: greyli/apiflask
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/greyli/apiflask
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/apiflask
copyright: Copyright &copy; 2021 <a href="https://greyli.com/en" target="_blank" rel="noopener">Grey Li</a>
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.tabbed
  - pymdownx.superfences
  - pymdownx.snippets
  - pymdownx.progressbar
  - toc:
        permalink: True
nav:
  - Home: index.md
  - Documentation Index: docs.md
  - Migrating from Flask: migrating.md
  - Basic Usage: usage.md
  - Swagger UI and Redoc: api-docs.md
  - Configuration: configuration.md
  - Examples: examples.md
  - API Reference:
    - APIFlask: api/app.md
    - APIBlueprint: api/blueprint.md
    - Decorators: api/decorators.md
    - Exceptions: api/exceptions.md
    - Schemas: api/schemas.md
    - Security: api/security.md
    - Utils: api/utils.md
  - Comparison and Motivations: comparison.md
  - Authors: authors.md
  - Changelog: changelog.md
  - Donate to APIFlask: https://opencollective.com/apiflask
  - WIP:
    - Schema and Fields: schema.md
    - Request Validation: request.md
    - Response Format: response.md
    - OpenAPI Generating: openapi.md
    - Authentication: security.md
    - Tutorial: tutorial/index.md
    - Snippets: snippets/index.md
    - External Tools: tools/index.md
    - Contributing Guide: contributing.md
    - Alternatives and Inspirations: alterinatives.md
plugins:
  - search
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          rendering:
            heading_level: 2
      watch:
        - apiflask
extra_css:
  - _assets/extra.css
