site_name: APIFlask
site_description: Web APIs for Flask.
site_url: https://apiflask.com
docs_dir: docs
theme:
  name: material
  custom_dir: docs/_templates
  logo: _assets/white-logo.png
  favicon: _assets/favicon.png
  palette:
    primary: deep orange
  icon:
    repo: fontawesome/brands/github
  language: en
repo_url: https://github.com/greyli/apiflask
repo_name: greyli/apiflask
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/greyli/apiflask
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/apiflask
copyright: Copyright &copy; 2021 <a href="https://greyli.com/en" target="_blank" rel="noopener">Grey Li</a>
markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.snippets
  - pymdownx.progressbar
  - toc:
        permalink: True
nav:
  - Home: index.md
  - Basic Usage: usage.md
  - Configuration: configuration.md
  - Migrating from Flask: flask.md
  - OpenAPI: openapi.md
  - Request Validation: request.md
  - Schema and Fields: schema.md
  - Security: security.md
  - Swagger UI and Redoc: swagger.md
  - Tutorial: tutorial/index.md
  - Examples: examples.md
  - Snippets: snippets/index.md
  - External Tools: tools/index.md
  - Contributing: contributing.md
  - Acknowledgement: acknowledgement.md
  - Authors: authors.md
  - Alternatives: alterinatives.md
  - API Reference:
    - APIFlask: api/app.md
    - APIBlueprint: api/blueprint.md
    - Decorators: api/decorators.md
    - Exceptions: api/exceptions.md
    - Schemas: api/schemas.md
    - Security: api/security.md
    - Utils: api/utils.md
  - Changelog: changelog.md
plugins:
  - search
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          rendering:
            heading_level: 2
      watch:
        - apiflask
extra_css:
  - _assets/extra.css
