blank_issues_enabled: false
contact_links:
  - name: Security issue
    url: withlihui+security@gmail.com
    about: Do not report security issues publicly. Email our security contact.
  - name: Questions, discussions, and ideas
    url: https://github.com/greyli/apiflask/discussions
    about: Discuss questions, ideas about your code or APIFlask itself on our GitHub Discussion.
  - name: Questions
    url: https://stackoverflow.com/questions/tagged/apiflask?tab=Frequent
    about: Search for or ask questions about your code on Stack Overflow.
